repos:
- repo: https://github.com/pycqa/flake8
  rev: 4.0.1
  hooks:
    - id: flake8
      args: [--config, setup.cfg]
      additional_dependencies:
        - flake8-bugbear
        - flake8-comprehensions
        - flake8-simplify

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-ast
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        exclude: ^.*\b(migrations)\b.*$

- repo: local
  hooks:
    - id: mypy
      name: mypy
      entry: "./.github/lint.sh check-mypy"
      # use require_serial so that script
      # is only called once per commit
      require_serial: true
      language: script
      # Print the number of files as a sanity-check
      verbose: true
      pass_filenames: false
      always_run: true
