version: '3.7'

services:
  db:
    container_name: ybs_postgres
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
  redis:
    image: redis:6.2-alpine
