version: '3.7'

services:
  web:
    image: ghcr.io/shamaevnn/ybs-summer-2022:latest
    container_name: ybs_backend
    restart: always
    ports:
      - 80:80
    env_file:
      - ./.env
    volumes:
      - .:/code
