"""empty message

Revision ID: 18bca1d63d9e
Revises: 65900b9b9c62
Create Date: 2022-06-26 15:45:51.235643

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "18bca1d63d9e"
down_revision = "65900b9b9c62"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "items_statistic",
        sa.Column("stat_id", postgresql.UUID(), nullable=False),
        sa.Column("id", postgresql.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("price", sa.BigInteger(), nullable=False),
        sa.Column("parent_id", postgresql.UUID(), nullable=True),
        sa.Column("type", sa.String(length=8), nullable=False),
        sa.Column("date", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.CheckConstraint("price >= 0", name="items_stat_price_check_gte_0"),
        sa.ForeignKeyConstraint(
            ["id"],
            ["items.id"],
            name="items_stat_id_f0ab547a_fk_items_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("stat_id"),
        sa.UniqueConstraint("id", "parent_id", "date", name="id_parent_id_date_uix"),
        sa.UniqueConstraint("id", "parent_id", "type", name="id_parent_id_type_uix"),
    )
    op.create_index(
        op.f("ix_items_statistic_id"), "items_statistic", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_items_statistic_parent_id"),
        "items_statistic",
        ["parent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_items_statistic_stat_id"), "items_statistic", ["stat_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_items_statistic_stat_id"), table_name="items_statistic")
    op.drop_index(op.f("ix_items_statistic_parent_id"), table_name="items_statistic")
    op.drop_index(op.f("ix_items_statistic_id"), table_name="items_statistic")
    op.drop_table("items_statistic")
    # ### end Alembic commands ###
