"""empty message

Revision ID: 64d3cad06c19
Revises:
Create Date: 2022-06-24 18:03:05.323817

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "64d3cad06c19"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "items",
        sa.Column("id", postgresql.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("price", sa.BigInteger(), nullable=True),
        sa.Column("parent_id", postgresql.UUID(), nullable=True),
        sa.Column("type", sa.String(length=8), nullable=False),
        sa.Column("date", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.CheckConstraint("price >= 0 or price is null", name="items_price_check_gte_0"),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["items.id"],
            name="items_parent_id_f0ab547a_fk_items_id",
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "parent_id", name="id_parent_id_uix"),
    )
    op.create_index(op.f("ix_items_id"), "items", ["id"], unique=False)
    op.create_index(op.f("ix_items_parent_id"), "items", ["parent_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_items_parent_id"), table_name="items")
    op.drop_index(op.f("ix_items_id"), table_name="items")
    op.drop_table("items")
    # ### end Alembic commands ###
