"""empty message

Revision ID: 65900b9b9c62
Revises: 64d3cad06c19
Create Date: 2022-06-25 15:42:57.771748

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "65900b9b9c62"
down_revision = "64d3cad06c19"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "items_parent_id_f0ab547a_fk_items_id", "items", type_="foreignkey"
    )
    op.create_foreign_key(
        "items_parent_id_f0ab547a_fk_items_id",
        "items",
        "items",
        ["parent_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "items_parent_id_f0ab547a_fk_items_id", "items", type_="foreignkey"
    )
    op.create_foreign_key(
        "items_parent_id_f0ab547a_fk_items_id",
        "items",
        "items",
        ["parent_id"],
        ["id"],
        initially="DEFERRED",
        deferrable=True,
    )
    # ### end Alembic commands ###
