"""empty message

Revision ID: 82515c670733
Revises: 18bca1d63d9e
Create Date: 2022-06-26 16:16:38.074273

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "82515c670733"
down_revision = "18bca1d63d9e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("id_parent_id_type_uix", "items_statistic", type_="unique")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "id_parent_id_type_uix", "items_statistic", ["id", "parent_id", "type"]
    )
    # ### end Alembic commands ###
