name: "checks"

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: install dependencies
        run: |
          pip install -r requirements.dev.txt && pip install -r requirements.txt
      - uses: pre-commit/action@v2.0.3
