name: "checks"

on: [push, pull_request]

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install python dependencies
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.5'
        run: |
          pip install -r requirements.dev.txt && pip install -r requirements.txt
          echo $(echo $DATABASE_URL) > .env

      - name: Check pre-commit actions
        uses: pre-commit/action@v2.0.3
